version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  preBuild:
    desc: Pre-build
    cmds:
      - go mod download
      - go mod tidy

  build-single:
    desc: Build single
    cmds:
      - goreleaser build --single-target --snapshot --clean --output dist/mdbook-asciidoc

  build:
    desc: Build
    cmds:
      - goreleaser build --snapshot --clean

  test:
    desc: Test
    deps: [ build-single ]
    cmds:
      - ./build-book.sh examples/test

  dependencyUpdates:
    desc: Show dependency updates
    deps: [ preBuild ]
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct
