version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  preBuild:
    desc: Pre-build
    cmds:
      - go mod download
      - go mod tidy

  build:
    desc: Build
    deps: [ preBuild ]
    cmds:
      - mkdir -p dist/bin
      - go build -o dist/bin/mdbook-asciidoc .
      #- goreleaser --snapshot --clean

  test:
    desc: Test
    deps: [ build ]
    cmds:
      - PATH=$PWD/dist/bin:$PATH mdbook build ${BOOK_DIR}
      - docker run --rm -u $(id -u):$(id -g) -v ${BOOK_DIR}/book/asciidoc/:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf -a allow-uri-read output.adoc
    env:
      BOOK_DIR:
        sh: echo "$PWD/examples/test"

  dependencyUpdates:
    desc: Show dependency updates
    deps: [ preBuild ]
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct
